function a = answers()
	a.impulse_image = ['Through the "tomatoes" picture,1D derivation'...
    'shows good outlines of the circle shapes. We can tell the slight vertical horizontal'...
    'difference from Dx or Dy'...
    'the second figure indicates that 2D derivation performs well in vertical and horizontal lines and circle'...
    'while Dxy works badly on lines'];
	a.gradmag = ['The magnitude picture shows very clear edge, but direction has many noise'];
	a.laplace = 'laplace figures catch very detailed but important features of original pictures.';
end
